### ISSUE TITLE
Memory consumption growing during operation

### ISSUE THREAD

**Issue by sumpfralle** [TargetHolding/bdsync#10]
Hi,

I recently noticed that the diffing process for my 375 GB volume causes the memory consumption of bdsync to grow up to about 2 GB. As far as I unerstand bdsync's operation I would assume that its memory usage is independent of the size of the volume to be processed. Thus I could imagine that some memory is not freed where it should be.
The memory consumption of the server process (on the target host) is not growing.

Besides this small detail bdsync is doing its job perfectly fine. Thank you!

Cheers,
Lars

**Comment by rolffokkens** [comment]
Seems somewhat memory-leaky indeed. Will look into this.

**Comment by rolffokkens** [comment]
Hi Lars,

Ik found a few memleaks. mtrace now assures me that these are gone. Could you give it a try?

Thanks,

Rolf

**Comment by rolffokkens** [comment]
Apart from the true memleaks, there's something else going on: bdsync uses extensive buffering of traffic between client and server to avoid any kind of congestion. A side effect of the current implementation is that this buffering results in excessive memory consumption when a lot of data is exchanged between client and server (speficically when --remdata is used). I'm working on a solution by earlier flushing data.

**Comment by rolffokkens** [comment]
Memory usage seems to be under control now completely. From start to finish (of a long bdsync) the total memory footprint stays < 20MB.

**Comment by sumpfralle** [comment]
Thank you! Now it runs even better ...
