### ISSUE TITLE
Clarify example on manpage

### ISSUE THREAD

**Issue by jniggemann** [TargetHolding/bdsync#16]
Having machine A and B, I want B/dev/sda1 to be the same as A/dev/sda1, i.e. I want to sync A to B. At the moment, B has slightly different content.

The manpage gives the following example:
> bdsync "ssh doe@foo.org bdsync --server" /dev/LOCDEV /dev/REMDEV | gzip > DEV.bdsync.gz

Do I execute this on machine A or on machine B? Or, with other words:  
Do I sync the client FROM the server, or TO the server?

**Comment by rolffokkens** [comment]
This has been fixed.
