### ISSUE TITLE
Error get_rd_queue: EOF 7

### ISSUE THREAD

**Issue by vetalit** [TargetHolding/bdsync#17]
Hi,

I am investigating bdsync as a backup solution from zfs to zfs volumes. For decrease load average I used cpuwatch, nice and ionice. I run bdsync like this:
/root/bdsync --blocksize=8192 --diffsize --remdata "ssh -i/root/.ssh/backup.key root@10.0.0.35 /root/cpuwatch 20 nice -n19 ionice -c2 -n7 /root/bdsync --server" /dev/zvol/backup/vps4/1105 /dev/zvol/zpool/1105_snapshot | /root/bdsync --diffsize --patch

But sometimes I have error:
get_rd_queue: EOF 7
do_patch: EOF(stdin)

**Comment by rolffokkens** [comment]
That 's a lot of details: zfs, cpuwatch, nice and ionice. I don't see a clear cause of this issue right away. Could you reduce the problem? For example: do you have the same problem when you're not using nice? ionice? cpuwatch? Without zfs? Can you identify any of these components as being the main contributer to the ussue? If you replace the '| /root/bdsync --diffsize --patch' by a simple '> /tmp/diff.bdsyn', what happens then?

**Comment by vetalit** [comment]
I found problem. This error occurred when the script was late with snapshot, so was not /dev/zvol/zpool/1105_snapshot

**Comment by rolffokkens** [comment]
Excellent!
