### ISSUE TITLE
Does not have built-in usage help

### ISSUE THREAD

**Issue by romanrm** [TargetHolding/bdsync#18]
```
$ ./bdsync --help
./bdsync: unrecognized option '--help'

$ ./bdsync 
Bad number of arguments 0
```
Could you please implement brief usage instructions with a list of the possible command line options and what they do?

Thanks!

**Comment by rolffokkens** [comment]
Thanks for pointing this out, could you check if the fix is OK?

**Comment by romanrm** [comment]
Thanks!
