### ISSUE TITLE
Help not recognized

### ISSUE THREAD

**Issue by jluttine** [TargetHolding/bdsync#20]
```
$ bdsync -H
bdsync: invalid option -- 'H'

$ bdsync --help
bdsync: unrecognized option '--help'
```

Version 0.10.1.

**Comment by jluttine** [comment]
Ah, it has been added after that release.. Could you make a new release so the release would have support for help?

**Comment by rolffokkens** [comment]
Thanks for your feedback! I made a new release 0.10.2.
