### ISSUE TITLE
Determine the progress of the operation?

### ISSUE THREAD

**Issue by sumpfralle** [TargetHolding/bdsync#21]
Hello,

I maintain [bdsync-manager](https://savannah.nongnu.org/projects/bdsync-manager/), which simplifies a quite common usage pattern of bdsync. *bdsync-manager* is surely not a very popular project, but it is useful (at least for me).

A feature that I am missing from time to time is the lack of progress updates available from the running bdsync process.

I am not sure, how this could be implemented in detail, but I could imagine one of the following approaches:
* write status output periodically to a configurable `--status-fd` (similar to `gpg`)
* write status output to stderr, whenever a process signal (e.g. `SIGUSR1`) is received (similar to `dd`)

The relevant status information could be the following:
* current position in the source file
* transferred data bytes (i.e. current size of the generated patch)
* uptime of the process
* bonus:
    * current position in the target file (I am not sure, if this is necessary)
    * size of the input and/or output file (this probably depends on the context)

CSV (e.g. tab separated columns, maybe as `key=value`) is probably sufficient as the output format. Or maybe even something fancy like JSON, in case this is trivial.

What do you think? Could this be a feature worth to be added?

I am afraid I am not in the position to provide an implementation for this feature. Thus I hope, that my description above could inspire you :)

Otherwise please feel free to close this issue. I just wanted to check, if my wish could find a fertile ground ...

**Comment by rolffokkens-th** [comment]
Sorry for the slow response. I agree this would be a nice feature indeed. Using an additional FD may be a solution, although stderr would be "easier". I'll look into this.

**Comment by rolffokkens-th** [comment]
Could you have a look at the progressindicator branch? It has a new option --progress which will provide progress feedback.

**Comment by sumpfralle** [comment]
Thank you for tackling this feature request!

I have the feeling, that it would be better to replace the progress percentage with the current input read position and the full size of the source. This will make it easy for a consumer to calculate the percentage on its own, but also allows to continue an aborted operation starting at the most recently reported input position.

What do you think?

**Comment by rolffokkens-th** [comment]
Instead op providing % as a progressindicator, I can easily change that to the numbers you're suggesting.
But starting an aborted operation at a specific position is not a feature that's in bdsync (yet). It's a tricky feature, because starting at a specific position should only be done if it's absolutely sure that the previously reported position is not only processed but also written to the bdsync file. That needs some thought.

**Comment by sumpfralle** [comment]
Indeed, partial operations are not trivial :)

The specific task of guaranteeing the state of output being written does not necessarily need to be within the scope of `bdsync`. At the moment I consider `bdsync` to be a quite low-level tool. Thus I would consider it to be appropriate, if it solves only the problems at the block level and leaves higher-level logic to other tools.

But this is your decision :)

**Comment by rolffokkens-th** [comment]
Could you check the latest in the progressindicator branch? I added the requested numbers in the --progress output.

Additional parameters specifying a specific position to start processing may be added later.
