### ISSUE TITLE
Leverage O_DIRECT

### ISSUE THREAD

**Issue by TimJDFletcher** [TargetHolding/bdsync#5]
Would it be possible to add an option to to open devices for reading and writing with O_DIRECT? This would prevent the large reads and writes to devices that bdsync does from polluting the buffer cache.

You can use old method of mapping a raw device to work round this but it's been deprecated since Linux 2.6.3

**Comment by rolffokkens** [comment]
Seems doable, I'll have a look into it.

**Comment by error10** [comment]
[O_DIRECT doesn't work with ZFS yet.](https://github.com/zfsonlinux/zfs/issues/224) So this would still have to fall back when unavailable.

**Comment by shodanshok** [comment]
Rather than using `O_DIRECT`, give a look at [this pull request](https://github.com/TargetHolding/bdsync/pull/12). I am using POSIX_FADV_DONTNEED to greatly decrease cache pollution.

**Comment by rolffokkens** [comment]
Implemented shodanshok's POSIX_FADV_DONTNEED, which reduces cache pollution substantially.
