### ISSUE TITLE
Please support MacOS X.

### ISSUE THREAD

**Issue by sbilly** [TargetHolding/bdsync#6]
As title.

**Comment by rolffokkens** [comment]
Not working on it myself, but this branch may be heading the right direction:
https://github.com/evansus/bdsync/tree/macosx

**Comment by sbilly** [comment]
Thank you.

**Comment by sbilly** [comment]
I does work yet.

**Comment by rolffokkens** [comment]
Consider sharing your concern with evansus who apparently tries to get it running on osx
