### ISSUE TITLE
vpread: Bad address

### ISSUE THREAD

**Issue by sumpfralle** [TargetHolding/bdsync#9]
Hi,

I am using v0.9 on amd64 (Debian).

I run something along the following lines:

    lvcreate -n source -L 20M lvm-vg1
    lvcreate -n target -L 24M lvm-vg1
    bdsync --diffsize "bdsync --server" /dev/lvm-vg1/source /dev/lvm-vg1/target >bd.patch

This results in the following error code:
    vpread: Bad address

Thus there seems to be a problem with the creation of a diff between a smaller source and a larger target device.

Thank you for this great tool!

Cheers,
Lars

**Comment by rolffokkens** [comment]
Hi Lars,

Thanks for your report!

This is probably a documentation error. bdsync uses ftruncate to resize a file, but this is not supported by block devices. There's no easy fox for this, each kind of block devices has specific ways for resizing (if possible at all).

So for sure I should mention this in de man page I think. And bdsync should return a better error message.

Cheers,
Rolf

**Comment by sumpfralle** [comment]
Hi Rolf,

thanks for this incredibly quick fix!

Just a sidenote: I expected that bdsync (in case of differing sizes) would just do the following:
1. calculate the effective size of the operation (the minimum of both sizes)
2. process the effective size in diff or in patch mode
3. ignore the remainder of the source or target blockdevice

This is the behaviour I expected. It is suitable for the following (real) use case:
* source: a raw block device (a partition)
* target: an LVM volume

I cannot shrink the size of the target device to the size of the source since the LVM volume's size is a multiple of the LVM extent size (here: 4 MB).

Currently bdsync would just refuse to deal with this situation, if I understand your commit properly.
Do you think that the above setup is worth to be supported?

thank you for your time,
Lars

**Comment by rolffokkens** [comment]
Never considered this use case, I think it's not that hard to support. I think I'll have it implemented next week.

**Comment by TimJDFletcher** [comment]
Thinking about this on the bus this morning, would it be worth added an option to sync only particular block ranges, eg bdsync --range 1024 65536

**Comment by sumpfralle** [comment]
@rolffokkens: thank you in advance - I would enjoy this feature a lot!

@TimJDFletcher: this could also be accomplished with the dmsetup utility. I have the feeling that this would be a clean and versatile solution for this specific problem.
Personally I will use dmsetup anyway in order to create a snapshot of the source device for the duration of the sync process.

**Comment by rolffokkens** [comment]
@sumpfralle: Latest commit adds support for --diffsize=minsize which should handle your case. Tests suggest it all works fine, but be careful.

**Comment by sumpfralle** [comment]
this is perfect - thanks a lot!
